Repository xPand4B/MiPa-Pool, pull requests merged in 2020-03, with the labels that each got.

#11 NTR - Expand frontend functions
  .psh.yaml
  app/Components/Common/Repositories/GenericRepository.php
  app/Components/User/Database/User.php
  app/Components/User/Database/factories/UserFactory.php
  app/Components/User/Database/migrations/2014_10_12_000000_create_users_table.php
  app/Components/User/Http/Controllers/Api/UserApiController.php
  app/Components/User/Http/Resources/UserResource.php
  app/Components/User/tests/Http/Resources/UserResourceTest.php
  dev-ops/common/actions/.clear.sh
  dev-ops/dev/actions/serve.sh
  public/js/app.js
  resources/js/src/App.vue
  resources/js/src/components/button-menu/index.vue
  resources/js/src/components/darkmode-switch/darkmode-switch.vue
  resources/js/src/components/icon/index.vue
  resources/js/src/components/profile/profile-image.vue
  resources/js/src/components/profile/profile-information.vue
  resources/js/src/components/profile/profile-initials.vue
  resources/js/src/components/profile/profile-topnav.vue
  resources/js/src/globalComponents.js
  resources/js/src/layouts/layout-auth/AuthLayout.vue
  resources/js/src/layouts/layout-auth/index.js
  resources/js/src/layouts/layout-default/index.vue
  resources/js/src/layouts/layout-default/navigation.vue
  resources/js/src/layouts/layout-default/sidebar-link.vue
  resources/js/src/layouts/layout-default/sidebar-toggle-mini.vue
  resources/js/src/layouts/layout-default/sidebar.vue
  resources/js/src/layouts/layout-default/topnav.vue
  resources/js/src/store/index.js
  resources/js/src/store/modules/sidebar.js
  resources/js/src/store/modules/user.js
Labels: enhancement, status::work-in-progress

#15 NTR - Author update
  composer.json
  package.json
Labels: enhancement, status::waiting-for-review

#14 NTR - Add jest setup
  .github/workflows/workflow.yml
  .gitignore
  dev-ops/common/actions/.unit-jest.sh
  dev-ops/dev/actions/unit-jest.sh
  dev-ops/dev/actions/unit.sh
  dev-ops/github/actions/unit-jest.sh
  package-lock.json
  package.json
  public/js/app.js
  resources/js/src/components/button-menu/button.menu.component.test.js
  resources/js/src/components/darkmode-switch/darkmode.switch.component.test.js
  resources/js/src/components/darkmode-switch/index.vue
  resources/js/src/components/icon/icon.component.test.js
  resources/js/src/components/index.js
  resources/js/src/components/index.test.js
  resources/js/src/components/profile/profile-image/index.vue
  resources/js/src/components/profile/profile-image/profile.image.component.test.js
  resources/js/src/components/profile/profile-information/index.vue
  resources/js/src/components/profile/profile-information/profile.information.component.test.js
  resources/js/src/components/profile/profile-initials/index.vue
  resources/js/src/components/profile/profile-initials/profile.initials.component.test.js
  resources/js/src/components/profile/profile-topnav/index.vue
  resources/js/src/components/profile/profile-topnav/profile.topnav.component.test.js
  resources/js/src/layouts/index.test.js
  resources/js/src/layouts/layout-default/index.vue
  resources/js/src/layouts/layout-default/layout-default-content/index.vue
  resources/js/src/layouts/layout-default/layout-default-content/layout.default.content.test.js
  resources/js/src/layouts/layout-default/layout-default-footer/index.vue
  resources/js/src/layouts/layout-default/layout-default-footer/layout.default.footer.test.js
  resources/js/src/layouts/layout-default/layout-default-navigation/index.vue
  resources/js/src/layouts/layout-default/layout-default-navigation/layout-default-navigation-sidebar/index.vue
  resources/js/src/layouts/layout-default/layout-default-navigation/layout-default-navigation-sidebar/layout.default.navigation.sidebar.test.js
  resources/js/src/layouts/layout-default/layout-default-navigation/layout-default-navigation-sidebar/sidebar-link.vue
  resources/js/src/layouts/layout-default/layout-default-navigation/layout-default-navigation-sidebar/sidebar-toggle-mini.vue
  resources/js/src/layouts/layout-default/layout-default-navigation/layout-default-navigation-topnav/index.vue
  resources/js/src/layouts/layout-default/layout-default-navigation/layout-default-navigation-topnav/layout.default.navigation.topnav.test.js
  resources/js/src/layouts/layout-default/layout-default-navigation/layout.default.navigation.test.js
  resources/js/src/layouts/layout-default/layout.default.test.js
  resources/js/src/pages/index.test.js
  resources/js/src/pages/order/create/index.vue
  resources/js/src/pages/order/create/order.create.page.test.js
  resources/js/src/pages/order/index/index.vue
  resources/js/src/pages/order/index/order.index.page.test.js
  resources/js/src/pages/user/index/index.vue
  resources/js/src/pages/user/index/user.index.page.test.js
  resources/js/src/routes/routes.js
  resources/js/src/store/index.test.js
  resources/js/src/store/modules/sidebar/index.js
  resources/js/src/store/modules/user/index.js
  resources/js/src/tests/feature/.gitkeep
  resources/js/src/tests/integration/.gitkeep
Labels: status::waiting-for-review

#18 NTR - Added update command
  .psh.yaml
  dev-ops/common/actions/install.sh
  dev-ops/common/actions/update.sh
  dev-ops/common/templates/.env.dist
Labels: status::waiting-for-review

#17 NTR - Changed migration table name to const from model
  app/Components/Menu/Database/Menu.php
  app/Components/Menu/Database/migrations/2019_02_05_170702_create_menus_table.php
  app/Components/Order/Database/Order.php
  app/Components/Order/Database/migrations/2019_01_12_122116_create_orders_table.php
  app/Components/Passport/Database/AuthCode.php
  app/Components/Passport/Database/Client.php
  app/Components/Passport/Database/PersonalAccessClient.php
  app/Components/Passport/Database/RefreshToken.php
  app/Components/Passport/Database/Token.php
  app/Components/Passport/Database/migrations/2016_06_01_000001_create_oauth_auth_codes_table.php
  app/Components/Passport/Database/migrations/2016_06_01_000002_create_oauth_access_tokens_table.php
  app/Components/Passport/Database/migrations/2016_06_01_000003_create_oauth_refresh_tokens_table.php
  app/Components/Passport/Database/migrations/2016_06_01_000004_create_oauth_clients_table.php
  app/Components/Passport/Database/migrations/2016_06_01_000005_create_oauth_personal_access_clients_table.php
  app/Components/User/Database/User.php
  app/Components/User/Database/migrations/2014_10_12_000000_create_users_table.php
  app/Console/Commands/stubs/model.stub
Labels: status::waiting-for-review

#16 NTR - Small refactor changes
  README.md
  app/Components/Common/Contracts/ApiControllerInterface.php
  app/Components/Common/Http/Controllers/Api/MiPaPoApiController.php
  app/Components/Common/Http/Middleware/Authenticate.php
  app/Components/Common/Http/Middleware/RedirectIfAuthenticated.php
  app/Components/Common/Http/Resources/BaseResource.php
  app/Components/Common/Http/Resources/ErrorResource.php
  app/Components/Common/Testing/CreatesApplication.php
  app/Components/User/Http/Resources/UserResource.php
  app/Components/User/tests/Http/Resources/UserResourceTest.php
  app/Console/Commands/AddApiRoutesCommand.php
  app/Console/Commands/AddWebRoutesCommand.php
  app/Console/Commands/MakeControllerCommand.php
  app/Console/Commands/MakeFactoryCommand.php
  app/Console/Commands/MakeRepositoryCommand.php
  app/Console/Commands/MakeRequestCommand.php
  app/Console/Commands/MakeResourceCommand.php
  app/Console/Commands/MakeTestCommand.php
  app/Console/Commands/stubs/controller.api.stub
  app/Console/Commands/stubs/repository.stub
  app/Console/Commands/stubs/resource.stub
  app/Console/Kernel.php
  app/Exceptions/Handler.php
  documentation/development/Development.md
  documentation/development/backend/00-Introduction.md
  documentation/development/backend/01-Api.md
  documentation/development/backend/02-Components.md
  documentation/development/backend/03-Core.md
  documentation/development/backend/Api.md
  documentation/development/frontend/00-Introduction.md
  documentation/update/README.md
  documentation/update/UPDATE-1.0.md
  documentation/update/UPDATE-1.1.md
Labels: status::waiting-for-review

#26 NTR - Small fixes
  app/Components/User/Http/Resources/UserResource.php
  app/Components/User/tests/Http/Resources/UserResourceTest.php
  public/js/app.js
  resources/js/src/components/profile/profile-topnav/index.vue
  resources/js/src/layouts/layout-default/index.vue
  resources/js/src/store/modules/sidebar/index.js
  resources/js/src/store/modules/user/index.js
Labels: status::waiting-for-review

#28 NTR - Renamed Sidebar-minimizer
  public/js/app.js
  resources/js/src/layouts/layout-default/layout-default-navigation/layout-default-navigation-sidebar/sidebar-toggle-mini.vue
  resources/js/src/store/modules/user/index.js
Labels: enhancement, status::waiting-for-review
